name: Flutter Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-macos:
    name: Build macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.2' # Specify your Flutter version
      - run: flutter pub get
        working-directory: text_encryption_flutter
      - run: flutter build macos
        working-directory: text_encryption_flutter

  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.2' # Specify your Flutter version
      - run: sudo apt-get install libgtk-3-dev
      - run: flutter pub get
        working-directory: text_encryption_flutter
      - run: flutter build linux
        working-directory: text_encryption_flutter

  build-web:
    name: Build Web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.2' # Specify your Flutter version
      - run: flutter pub get
        working-directory: text_encryption_flutter
      - run: flutter build web
        working-directory: text_encryption_flutter
