name: Flutter Build and Package

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-windows:
    name: Build and Package Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout code

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.2'

      - name: Install Dependencies
        run: |
          choco install cmake --installargs '"ADD_CMAKE_TO_PATH=System"'
          choco install ninja
          choco install visualstudio2019buildtools --version=16.0 --package-parameters "--add Microsoft.VisualStudio.Workload.MSBuildTools"

      - name: Build Windows app
        run: flutter build windows
        working-directory: text_encryption_flutter

      - name: Create Windows installer
        run: |
          $outputDir = 'text_encryption_flutter/build/windows/runner/Release'
          & 'C:\Program Files\Inno Setup 6\ISCC.exe' 'path_to_inno_setup_script.iss'
        working-directory: text_encryption_flutter

      - name: Upload Windows installer
        uses: actions/upload-artifact@v3
        with:
          name: windows-installer
          path: text_encryption_flutter/build/windows/runner/Release/*.exe

  build-macos:
    name: Build and Package macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout code

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.2'

      - run: flutter pub get
        working-directory: text_encryption_flutter

      - run: flutter build macos
        working-directory: text_encryption_flutter

      - name: Create macOS .dmg
        run: |
          brew install create-dmg
          create-dmg 'text_encryption_flutter/build/macos/Build/Products/Release/text_encryption.app' \
          --out="$HOME/text_encryption.dmg"

      - name: Upload macOS .dmg
        uses: actions/upload-artifact@v3
        with:
          name: macos-dmg
          path: $HOME/text_encryption.dmg

  build-linux:
    name: Build and Package Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout code

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.2'

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake \
            ninja-build \
            build-essential \
            pkg-config \
            libgtk-3-dev \
            liblzma-dev

      - run: flutter pub get
        working-directory: text_encryption_flutter

      - run: flutter build linux
        working-directory: text_encryption_flutter

      - name: Create Linux .tar.gz
        run: |
          cd text_encryption_flutter/build/linux/x64/release/bundle
          tar --warning=no-file-changed -czvf text_encryption.tar.gz .

      - name: Upload Linux .tar.gz
        uses: actions/upload-artifact@v3
        with:
          name: linux-tarball
          path: text_encryption_flutter/build/linux/x64/release/bundle/text_encryption.tar.gz
