name: Build Flutter Web Version

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-web:
    name: Build Flutter Web
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install Flutter manually
      - name: Install Flutter
        run: |
          git clone https://github.com/flutter/flutter.git -b stable
          echo "$PWD/flutter/bin" >> $GITHUB_PATH
          export PATH="$PWD/flutter/bin:$PATH"
          flutter --version

      # Step 3: Change directory to the Flutter project folder
      - name: Change directory to Flutter project
        working-directory: text_encryption_flutter
        run: echo "Changed directory to text_encryption_flutter"

      # Step 4: Enable web support
      - name: Enable web support
        working-directory: text_encryption_flutter
        run: flutter config --enable-web

      # Step 5: Install dependencies
      - name: Install dependencies
        working-directory: text_encryption_flutter
        run: flutter pub get

      # Step 6: Build the web version
      - name: Build Flutter Web
        working-directory: text_encryption_flutter
        run: flutter build web --web-renderer html

      # Step 7: Create a zip of the build output
      - name: Zip Build Folder
        working-directory: text_encryption_flutter/build/web
        run: zip -r web_build.zip .

      # Step 8: Upload the zip as an artifact
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: flutter-web-build
          path: text_encryption_flutter/build/web/web_build.zip
