name: Build Flutter Web

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-web:
    name: Build Flutter Web
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install Flutter manually
      - name: Install Flutter
        run: |
          git clone https://github.com/flutter/flutter.git -b stable
          echo "$PWD/flutter/bin" >> $GITHUB_PATH
          export PATH="$PWD/flutter/bin:$PATH"
          flutter --version

      # Change to the Flutter project directory
      - name: Change directory to Flutter project
        working-directory: text_encryption_flutter
        run: echo "Changed directory to text_encryption_flutter"

      # Enable web support
      - name: Enable web support
        working-directory: text_encryption_flutter
        run: flutter config --enable-web

      # Get Flutter dependencies
      - name: Install dependencies
        working-directory: text_encryption_flutter
        run: flutter pub get

      # Build the Flutter web project
      - name: Build for web
        working-directory: text_encryption_flutter
        run: flutter build web

      # Upload build artifacts
      - name: Upload web build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: flutter-web-build
          path: text_encryption_flutter/build/web
