name: Build and Package Flutter App

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-macos:
    name: Build macOS
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.10'

      - name: Install dependencies
        run: flutter pub get

      - name: Build macOS app
        run: flutter build macos

      - name: Create macOS .dmg
        run: |
          brew install create-dmg
          create-dmg 'build/macos/Build/Products/Release/YourApp.app' $HOME/YourApp.dmg

      - name: Upload macOS .dmg
        uses: actions/upload-artifact@v3
        with:
          name: macos-dmg
          path: $HOME/YourApp.dmg

  build-windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.10'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Windows app
        run: flutter build windows

      - name: Upload Windows executable
        uses: actions/upload-artifact@v3
        with:
          name: windows-exe
          path: build/windows/runner/Release/YourApp.exe

  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.10'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Linux app
        run: flutter build linux

      - name: Create Linux .tar.gz
        run: |
          cd build/linux/x64/release/bundle
          tar -czvf YourApp.tar.gz YourApp

      - name: Upload Linux .tar.gz
        uses: actions/upload-artifact@v3
        with:
          name: linux-tarball
          path: build/linux/x64/release/bundle/YourApp.tar.gz
